<!DOCTYPE html>
<html lang="en" dir="ltr">
<head><meta charset="UTF-8"><title>{{ $docTitle }} {{ $docNumber }}</title>
<style>
@font-face{font-family:Invoice;src:url('{{ $fontRegular }}')}@font-face{font-family:Invoice;src:url('{{ $fontBold }}');font-weight:700}
*{box-sizing:border-box}body{font-family:Invoice,sans-serif;color:#1A1730;font-size:11px;line-height:1.6;margin:0}.header{background:#1E1B3A;color:#fff;padding:12px 26px}.header table,.info-box table,.rows,.totals{width:100%;border-collapse:collapse}.brand{font-size:18px;font-weight:700}.sub{font-size:10px;color:#C9D6FF}.meta{text-align:right;font-size:10px;line-height:1.8}.meta b{color:#E8C766}.body{padding:12px 26px}.info-box{background:#F3F0FA;border-radius:6px;padding:8px 16px;margin-bottom:10px}.info-box td{padding:3px 0}.label{display:block;color:#6B6584;font-size:9px}.section-title{font-size:12px;color:#2D2657;border-bottom:2px solid #EDE9F7;padding-bottom:4px;margin:10px 0 5px}.rows th{background:#F7F5F1;color:#6B6584;font-size:9px;padding:4px 8px;text-align:left;border-bottom:1px solid #E4DFD3}.rows td{padding:4px 8px;border-bottom:1px solid #EDEAE2}.amount{text-align:right;font-weight:700;white-space:nowrap}.rate{color:#6B6584;font-size:9px}.totals{margin-top:3px}.totals td{padding:5px 10px}.grand{background:#F7EFD2}.grand td{font-size:13px;font-weight:700}.contact{margin-top:8px;background:#F7F5F1;border-radius:6px;padding:8px 16px;font-size:9.5px}
</style></head>
<body><div class="header"><table><tr><td class="brand">NavraCar<div class="sub">{{ $docTitle }}</div></td><td class="meta">Number: <b>{{ $docNumber }}</b><br>Issue date: {{ $docDate }}<br>@if($validUntil)Valid until: <b>{{ $validUntil }}</b>@endif</td></tr></table></div>
<div class="body"><div class="info-box"><table><tr><td style="width:50%"><span class="label">Customer</span>{{ $customerName }}</td><td style="width:50%"><span class="label">Phone</span>{{ $customerPhone }}</td></tr>@if($customerEmail || $carLabel)<tr><td>@if($customerEmail)<span class="label">Email</span>{{ $customerEmail }}@endif</td><td>@if($carLabel)<span class="label">Vehicle</span>{{ $carLabel }}{{ $categoryLabel ? ' — '.$categoryLabel : '' }}@endif</td></tr>@endif</table></div>
<h3 class="section-title">Cost breakdown</h3><table class="rows"><thead><tr><th>#</th><th>Description</th><th>Rate / notes</th><th class="amount">Amount</th></tr></thead><tbody>@foreach($breakdown as $i => $row)<tr><td>{{ $i + 1 }}</td><td>{{ $row['label'] ?? '' }}</td><td class="rate">{{ $row['rate'] ?? '' }}</td><td class="amount">{{ $row['amount'] ?? '' }}</td></tr>@endforeach</tbody></table>
<h3 class="section-title">Summary</h3><table class="totals">@foreach($totalsSummary as $row)<tr @if(!empty($row['emphasis'])) class="grand" @endif><td>{{ $row['label'] }}</td><td class="amount">{{ $row['amount'] }}</td></tr>@endforeach</table>
<div class="contact"><b>Contact</b><br>Iran: {{ $contact['iran'] }}<br>UAE: {{ $contact['uae'] }}<br>Tehran office: {{ $contact['tehran'] }}<br>Website: navracar.com</div></div></body></html>
